### ISSUE TITLE
Tuple in return type signature showing as "uple", because of lstrip.

### ISSUE THREAD

**Issue by ID56** [ml-tooling/lazydocs#19]
**Describe the bug:**

When the return type is tuple, it is being rendered as "uple" instead.

**Expected behaviour:**
I expect it to show tuple.

**Steps to reproduce the issue:**
```
def foo(x : int = 1, y: int = 2, z: tuple = (0.001, 2)) -> tuple:
    """Some function.

    Args:
        x (int, optional): An integer. Defaults to 1.
        y (int, optional): An integer. Defaults to 2.
        z (tuple, optional): Tuple. Defaults to (0.001, 2).

    Returns:
        tuple: (x, y).
    """     
    return (x, y)
```

Lazydoc renders this as:

![image](https://user-images.githubusercontent.com/38450043/121246566-216e8080-c8c3-11eb-919d-2a2397649cec.png)

Note the "uple".

**Technical details:**

- Host Machine OS (Windows/Linux/Mac): Linux
- Browser (Chrome/Firefox/Safari): Firefox

**Possible Fix:**
Again, seems to be a cosmetic issue like #18 

**Additional context:**

**Comment by ID56** [comment]
Out of curiosity, I took a glance through your source code. The problem is quite easy to trace; it comes from [here](https://github.com/ml-tooling/lazydocs/blob/main/src/lazydocs/generation.py#L147).

```
return_type = return_type.lstrip("typing.")
```

What this does is if return type starts with any of the characters in (t, y, p, i, n, g, .) it'll be stripped. E.g:

```
"tuple".lstrip("typing") --> "uple"
```

Even more problematic: one of the most basic types, "int" has all 3 characters among (t, y, p, i, n, g, .) and thus gets completely deleted.

```
"int".lstrip("typing") --> ""
```
The fix would be to swap out lstrip, which has a potentially dangerous behaviour, with some re expression.

**Comment by LukasMasuch** [comment]
@ID56 Thanks for reporting this issue as well :) I have pushed a small fix for this issue here: https://github.com/ml-tooling/lazydocs/commit/dd8706583b53310730f4288334129a8bd7f3c43f Will be included in the next release.
