### ISSUE TITLE
Doesn't find absolute imports to parts of a module when Python itself does

### ISSUE THREAD

**Issue by marcelr-bk** [ml-tooling/lazydocs#39]
Hello,
I have a structure like this:

```
foo
`-- __init__.py
`-- common.py
`-- bar.py
```

where in `bar.py` I do `import foo.common`.
When running lazydocs, I get the message `Failed to generate docs for module foo.bar: AttributeError("module 'foo' has no attribute 'common'",)
`

However, when just starting a new Python shell and doing `import foo.bar` there are no complaints, so I'd expect it to work in Lazydocs as well.

Anything that I'm missing, or is this a bug?

**Comment by thucngyyen** [comment]
you probably need to add  PYTHONPATH = path/to/module/

**Comment by pauloburke** [comment]
I'm also running into this issue when using the generate_docs function
