### ISSUE TITLE
Comments "in between" functions for structuring doc

### ISSUE THREAD

**Issue by Hermann-SW** [ml-tooling/lazydocs#49]
**Feature description:**

Add ability to add comment for generated lazydocs output between functions.

**Problem and motivation:**

Allows to structure groups of functions.

**Is this something you're interested in working on?**

No experience with act.

What I did sofar is to use dummy function definitions to achieve the requested feature as workaround:
```
...
    return int(lcm(p-1, q-1))


def SECTION5():
    '''
    Functions on factorization dictionaries.

    [as returned by sympy.factorint() (in rsa[x][4] for p-1 and rsa[x][5] for q-1) ]
    '''
    return
def dict_int(d):
...
```

This works, but creates a dummy function for each inter function comment, and one has to remember to have the final return.

**Comment by Hermann-SW** [comment]
I don't know the process, shouldn't somebody review this issue before amarking stale and auto closing?

**Comment by epogrebnyak** [comment]
This something you can achieve with Sphinx and mkdocstrings. In mkdocstrings in particular you can write the comment in markdown, then insert function docs. 

Also from a broader perspective grouping inside module may be a sign you might split the module in parts, or add classes that hold groups of methods.
