### ISSUE TITLE
Global variable comment is ignored for lazydocs output

### ISSUE THREAD

**Issue by Hermann-SW** [ml-tooling/lazydocs#50]
**Describe the bug:**

Global variable comment is ignored for lazydocs output.

**Expected behaviour:**

In gobal variables section, global variable comment should show as function comment shows for functions.

**Steps to reproduce the issue:**

Run lazydocs on glob.py:
```
glob = "foobar"
"""
    global string value
"""
glob2 = "foobar2"
"""
    global string value2
"""

def f() -> str:
    """
    returns:
        some string
    """
    return glob
```

"global string ..." comments do not show in generated lazydocs output:
<img src="https://stamm-wilbrandt.de/en/globvar_bug_lazydocs.png">

**Technical details:**

**Possible Fix:**

**Additional context:**

**Comment by Hermann-SW** [comment]
I don't know the process, but shouldn't somebody review this issue before marking stale and auto closing?

**Comment by rmnldwg** [comment]
I would also love so see the ability to document global variables 👍🏻

Really cool package by the way! I just discovered it and love its simplicity.
