### ISSUE TITLE
Create one page md file for all the docstrings

### ISSUE THREAD

**Issue by ventouris** [ml-tooling/lazydocs#52]
**Feature description:**

Instead of creating several md files for each module, lazydocs create one single page with everything in there. 

**Problem and motivation:**

I am currently working on several small projects that might have 2-4 functions per file. I want to gather all the documentation in a single page where I can easily find the module/function/class I want to without jumping from one page to the other. 

**Is this something you're interested in working on?**

Probably no, due to lack of lazydocs code experience.

**Comment by epogrebnyak** [comment]
Does importing all functions to a single module then running lazydocs on it work for you? Even with import *. 

This is probably something you can do on your end with existing lazydoc functionality.
