### ISSUE TITLE
Is lazydocs repo still maintained?

### ISSUE THREAD

**Issue by Hermann-SW** [ml-tooling/lazydocs#54]
I see that no real changes were done in 2023 and 2022.
So is lazydocs still maintained?

**Comment by Hermann-SW** [comment]
This seems to confirm that lazydocs is not maintained anymore ... :-(

**Comment by Hermann-SW** [comment]
This seems to confirm that lazydocs is not maintained anymore ... :-(

**Comment by Hermann-SW** [comment]
obviously unmaintained

**Comment by epogrebnyak** [comment]
The package seems stable - what kind of maintenance are you expecting? The neibouring issue about stubs is probably it of scope.

**Comment by Hermann-SW** [comment]
> The package seems stable 

Good.


> - what kind of maintenance are you expecting? 

That at least somebody decides or decides not to work issues.
All issues just get resolved by marking stale and closing after 90 days.
That is what I would name unmaintained.

**Comment by Hermann-SW** [comment]
unmaintained
